spec:
  template:
    spec:
      containers:
        - name: vertx
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: "/api/health/liveness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreashold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/api/health/readiness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreashold: 1
            timeoutSeconds: 1